Disable OpenJDK 6 from Travis CI
Travis CI build keeps failing as follows for OpenJDK 6:

Using /home/travis/.sbt/0.12.1 as sbt dir, -sbt-dir to override.
java.io.IOException: Cannot run program "sh": java.io.IOException: error=12, Cannot allocate memory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:475)
	at java.lang.Runtime.exec(Runtime.java:610)
	at java.lang.Runtime.exec(Runtime.java:483)
	at jline.UnixTerminal.exec(UnixTerminal.java:292)
	at jline.UnixTerminal.stty(UnixTerminal.java:268)
	at jline.UnixTerminal.initializeTerminal(UnixTerminal.java:71)
	at jline.Terminal.setupTerminal(Terminal.java:75)
	at jline.Terminal.getTerminal(Terminal.java:26)
	at sbt.ConsoleLogger$.ansiSupported(ConsoleLogger.scala:112)
	at sbt.ConsoleLogger$.<init>(ConsoleLogger.scala:107)
	at sbt.ConsoleLogger$.<clinit>(ConsoleLogger.scala)
	at sbt.StandardMain$.<init>(Main.scala:52)
	at sbt.StandardMain$.<clinit>(Main.scala)
	at sbt.xMain.run(Main.scala:26)
	at xsbt.boot.Launch$.run(Launch.scala:55)
	at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
	at xsbt.boot.Launch$.launch(Launch.scala:69)
	at xsbt.boot.Launch$.apply(Launch.scala:16)
	at xsbt.boot.Boot$.runImpl(Boot.scala:31)
	at xsbt.boot.Boot$.main(Boot.scala:20)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.io.IOException: java.io.IOException: error=12, Cannot allocate memory
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:164)
	at java.lang.ProcessImpl.start(ProcessImpl.java:81)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:468)
	... 20 more

Disable the configuration from Travis control file.

Signed-off-by: Pekka Enberg <penberg@valotrading.com>